export interface IClub {
  id: string;
  name: string;
  type: string;
  clubSpeed: number;
  attackAngle: number;
  ballSpeed: number;
  smash: number;
  VLA: number;
  spin: number;
  peakHeight: number;
  descentAngle: number;
  carry: number;
  extraText?: string;
}

const pgaTourAverages = {
  Driver: {
    id: 'Driver',
    name: 'Driver',
    type: 'wood',
    clubSpeed: 115,
    attackAngle: -0.9,
    ballSpeed: 171,
    smash: 1.49,
    VLA: 10.4,
    spin: 2545,
    peakHeight: 35,
    descentAngle: 39,
    carry: 282,
  },
  '3-wood': {
    id: '3-wood',
    name: '3 Wood',
    type: 'wood',
    clubSpeed: 110,
    attackAngle: -2.3,
    ballSpeed: 162,
    smash: 1.47,
    VLA: 9.3,
    spin: 3663,
    peakHeight: 32,
    descentAngle: 44,
    carry: 249,
  },
  '5-wood': {
    id: '5-wood',
    name: '5 Wood',
    type: 'wood',
    clubSpeed: 106,
    attackAngle: -2.5,
    ballSpeed: 156,
    smash: 1.47,
    VLA: 9.7,
    spin: 4322,
    peakHeight: 33,
    descentAngle: 48,
    carry: 236,
  },
  Hybrid: {
    id: 'Hybrid',
    name: 'Hybrid',
    type: 'hybrid',
    extraText: '15-18°',
    clubSpeed: 102,
    attackAngle: -2.4,
    ballSpeed: 149,
    smash: 1.47,
    VLA: 10.2,
    spin: 4587,
    peakHeight: 31,
    descentAngle: 49,
    carry: 231,
  },
  '3-iron': {
    id: '3-iron',
    name: '3 Iron',
    type: 'iron',
    clubSpeed: 100,
    attackAngle: -2.5,
    ballSpeed: 145,
    smash: 1.46,
    VLA: 10.3,
    spin: 4404,
    peakHeight: 30,
    descentAngle: 48,
    carry: 218,
  },
  '4-iron': {
    id: '4-iron',
    name: '4 Iron',
    type: 'iron',
    clubSpeed: 98,
    attackAngle: -2.9,
    ballSpeed: 140,
    smash: 1.44,
    VLA: 10.8,
    spin: 4782,
    peakHeight: 31,
    descentAngle: 49,
    carry: 209,
  },
  '5-iron': {
    id: '5-iron',
    name: '5 Iron',
    type: 'iron',
    clubSpeed: 96,
    attackAngle: -3.4,
    ballSpeed: 135,
    smash: 1.41,
    VLA: 12.1,
    spin: 5280,
    peakHeight: 33,
    descentAngle: 50,
    carry: 199,
  },
  '6-iron': {
    id: '6-iron',
    name: '6 Iron',
    type: 'iron',
    clubSpeed: 94,
    attackAngle: -3.7,
    ballSpeed: 130,
    smash: 1.39,
    VLA: 14.0,
    spin: 6204,
    peakHeight: 32,
    descentAngle: 50,
    carry: 188,
  },
  '7-iron': {
    id: '7-iron',
    name: '7 Iron',
    type: 'iron',
    clubSpeed: 92,
    attackAngle: -3.9,
    ballSpeed: 123,
    smash: 1.34,
    VLA: 16.1,
    spin: 7124,
    peakHeight: 34,
    descentAngle: 51,
    carry: 176,
  },
  '8-iron': {
    id: '8-iron',
    name: '8 Iron',
    type: 'iron',
    clubSpeed: 89,
    attackAngle: -4.2,
    ballSpeed: 118,
    smash: 1.33,
    VLA: 17.8,
    spin: 8078,
    peakHeight: 34,
    descentAngle: 51,
    carry: 164,
  },
  '9-iron': {
    id: '9-iron',
    name: '9 Iron',
    type: 'iron',
    clubSpeed: 87,
    attackAngle: -4.3,
    ballSpeed: 112,
    smash: 1.29,
    VLA: 20.0,
    spin: 8793,
    peakHeight: 32,
    descentAngle: 52,
    carry: 152,
  },
  PW: {
    id: 'PW',
    name: 'PW',
    type: 'iron',
    clubSpeed: 84,
    attackAngle: -4.7,
    ballSpeed: 104,
    smash: 1.24,
    VLA: 23.7,
    spin: 9316,
    peakHeight: 32,
    descentAngle: 52,
    carry: 142,
  },
};

const lpgaTourAverages = {
  Driver: {
    id: 'Driver',
    name: 'Driver',
    type: 'wood',
    clubSpeed: 96,
    attackAngle: 2.8,
    ballSpeed: 143,
    smash: 1.49,
    VLA: 12.6,
    spin: 2506,
    peakHeight: 26,
    descentAngle: 36,
    carry: 223,
  },
  '3-wood': {
    id: '3-wood',
    name: '3 Wood',
    type: 'wood',
    clubSpeed: 92,
    attackAngle: -0.8,
    ballSpeed: 135,
    smash: 1.47,
    VLA: 11.6,
    spin: 2595,
    peakHeight: 25,
    descentAngle: 38,
    carry: 200,
  },
  '5-wood': {
    id: '5-wood',
    name: '5 Wood',
    type: 'wood',
    clubSpeed: 90,
    attackAngle: -1.6,
    ballSpeed: 130,
    smash: 1.46,
    VLA: 12.3,
    spin: 4320,
    peakHeight: 25,
    descentAngle: 43,
    carry: 189,
  },
  '7-wood': {
    id: '7-wood',
    name: '7 Wood',
    type: 'wood',
    clubSpeed: 85,
    attackAngle: -3.0,
    ballSpeed: 123,
    smash: 1.45,
    VLA: 12.7,
    spin: 4693,
    peakHeight: 25,
    descentAngle: 46,
    carry: 174,
  },
  Hybrid: {
    id: 'Hybrid',
    name: 'Hybrid',
    type: 'hybrid',
    clubSpeed: 87,
    attackAngle: -1.9,
    ballSpeed: 125,
    smash: 1.44,
    VLA: 13.9,
    spin: 4505,
    peakHeight: 25,
    descentAngle: 45,
    carry: 178,
  },
  '4-iron': {
    id: '4-iron',
    name: '4 Iron',
    type: 'iron',
    clubSpeed: 82,
    attackAngle: -1.7,
    ballSpeed: 118,
    smash: 1.43,
    VLA: 13.9,
    spin: 4608,
    peakHeight: 25,
    descentAngle: 43,
    carry: 175,
  },
  '5-iron': {
    id: '5-iron',
    name: '5 Iron',
    type: 'iron',
    clubSpeed: 81,
    attackAngle: -2.0,
    ballSpeed: 114,
    smash: 1.42,
    VLA: 14.6,
    spin: 4966,
    peakHeight: 25,
    descentAngle: 46,
    carry: 166,
  },
  '6-iron': {
    id: '6-iron',
    name: '6 Iron',
    type: 'iron',
    clubSpeed: 80,
    attackAngle: -2.3,
    ballSpeed: 111,
    smash: 1.41,
    VLA: 16.7,
    spin: 5904,
    peakHeight: 25,
    descentAngle: 46,
    carry: 155,
  },
  '7-iron': {
    id: '7-iron',
    name: '7 Iron',
    type: 'iron',
    clubSpeed: 78,
    attackAngle: -2.5,
    ballSpeed: 106,
    smash: 1.38,
    VLA: 18.5,
    spin: 6630,
    peakHeight: 26,
    descentAngle: 47,
    carry: 143,
  },
  '8-iron': {
    id: '8-iron',
    name: '8 Iron',
    type: 'iron',
    clubSpeed: 76,
    attackAngle: -2.8,
    ballSpeed: 102,
    smash: 1.36,
    VLA: 20.8,
    spin: 7413,
    peakHeight: 27,
    descentAngle: 47,
    carry: 133,
  },
  '9-iron': {
    id: '9-iron',
    name: '9 Iron',
    type: 'iron',
    clubSpeed: 74,
    attackAngle: -3.2,
    ballSpeed: 95,
    smash: 1.3,
    VLA: 23.5,
    spin: 7605,
    peakHeight: 27,
    descentAngle: 48,
    carry: 123,
  },
  PW: {
    id: 'PW',
    name: 'PW',
    type: 'iron',
    clubSpeed: 72,
    attackAngle: -3.2,
    ballSpeed: 88,
    smash: 1.25,
    VLA: 25.2,
    spin: 8465,
    peakHeight: 27,
    descentAngle: 48,
    carry: 111,
  },
};

export const statsForClub = (club: string, tour: string) => {
  const allStats: { [key: string]: IClub } =
    tour.toUpperCase() === 'PGA' ? pgaTourAverages : lpgaTourAverages;
  // Returns the stats for a single club
  return allStats[club];
};

export const allClubs = (tour: string) => {
  const allClubs: { [key: string]: IClub } =
    tour.toUpperCase() === 'PGA' ? pgaTourAverages : lpgaTourAverages;
  // Return all club information
  return Object.values(allClubs);
};
