export interface IClub {
  id: string;
  name: string;
  type: string;
  clubSpeed: number;
  attackAngle: number;
  ballSpeed: number;
  smash: number;
  VLA: number;
  spin: number;
  peakHeight: number;
  descentAngle: number;
  carry: number;
  extraText?: string;
}

const pgaTourAverages = {
  Driver: {
    id: 'Driver',
    name: 'Driver',
    type: 'wood',
    clubSpeed: 113,
    attackAngle: -1.3,
    ballSpeed: 167,
    smash: 1.48,
    VLA: 10.9,
    spin: 2686,
    peakHeight: 32,
    descentAngle: 38,
    carry: 275,
  },
  '3-wood': {
    id: '3-wood',
    name: '3 Wood',
    type: 'wood',
    clubSpeed: 107,
    attackAngle: -2.9,
    ballSpeed: 158,
    smash: 1.48,
    VLA: 9.2,
    spin: 2655,
    peakHeight: 30,
    descentAngle: 43,
    carry: 243,
  },
  '5-wood': {
    id: '5-wood',
    name: '5 Wood',
    type: 'wood',
    clubSpeed: 103,
    attackAngle: -3.3,
    ballSpeed: 152,
    smash: 1.47,
    VLA: 9.4,
    spin: 4350,
    peakHeight: 31,
    descentAngle: 47,
    carry: 230,
  },
  Hybrid: {
    id: 'Hybrid',
    name: 'Hybrid',
    type: 'hybrid',
    extraText: '15-18°',
    clubSpeed: 100,
    attackAngle: -3.5,
    ballSpeed: 146,
    smash: 1.46,
    VLA: 10.2,
    spin: 4437,
    peakHeight: 29,
    descentAngle: 47,
    carry: 225,
  },
  '3-iron': {
    id: '3-iron',
    name: '3 Iron',
    type: 'iron',
    clubSpeed: 98,
    attackAngle: -3.1,
    ballSpeed: 142,
    smash: 1.45,
    VLA: 10.4,
    spin: 4630,
    peakHeight: 27,
    descentAngle: 46,
    carry: 212,
  },
  '4-iron': {
    id: '4-iron',
    name: '4 Iron',
    type: 'iron',
    clubSpeed: 96,
    attackAngle: -3.4,
    ballSpeed: 137,
    smash: 1.43,
    VLA: 11,
    spin: 4836,
    peakHeight: 28,
    descentAngle: 48,
    carry: 203,
  },
  '5-iron': {
    id: '5-iron',
    name: '5 Iron',
    type: 'iron',
    clubSpeed: 94,
    attackAngle: -3.7,
    ballSpeed: 132,
    smash: 1.41,
    VLA: 12.1,
    spin: 5361,
    peakHeight: 31,
    descentAngle: 49,
    carry: 194,
  },
  '6-iron': {
    id: '6-iron',
    name: '6 Iron',
    type: 'iron',
    clubSpeed: 92,
    attackAngle: -4.1,
    ballSpeed: 127,
    smash: 1.38,
    VLA: 14.1,
    spin: 6231,
    peakHeight: 30,
    descentAngle: 50,
    carry: 183,
  },
  '7-iron': {
    id: '7-iron',
    name: '7 Iron',
    type: 'iron',
    clubSpeed: 90,
    attackAngle: -4.3,
    ballSpeed: 120,
    smash: 1.33,
    VLA: 16.3,
    spin: 7097,
    peakHeight: 32,
    descentAngle: 50,
    carry: 172,
  },
  '8-iron': {
    id: '8-iron',
    name: '8 Iron',
    type: 'iron',
    clubSpeed: 87,
    attackAngle: -4.5,
    ballSpeed: 115,
    smash: 1.32,
    VLA: 18.1,
    spin: 7998,
    peakHeight: 31,
    descentAngle: 50,
    carry: 160,
  },
  '9-iron': {
    id: '9-iron',
    name: '9 Iron',
    type: 'iron',
    clubSpeed: 85,
    attackAngle: -4.7,
    ballSpeed: 109,
    smash: 1.28,
    VLA: 20.4,
    spin: 8647,
    peakHeight: 30,
    descentAngle: 51,
    carry: 148,
  },
  PW: {
    id: 'PW',
    name: 'PW',
    type: 'iron',
    clubSpeed: 83,
    attackAngle: -5.0,
    ballSpeed: 102,
    smash: 1.23,
    VLA: 24.2,
    spin: 9304,
    peakHeight: 29,
    descentAngle: 52,
    carry: 136,
  },
};

const lpgaTourAverages = {
  Driver: {
    id: 'Driver',
    name: 'Driver',
    type: 'wood',
    clubSpeed: 94,
    attackAngle: 3.0,
    ballSpeed: 140,
    smash: 1.48,
    VLA: 13.2,
    spin: 2611,
    peakHeight: 25,
    descentAngle: 37,
    carry: 218,
  },
  '3-wood': {
    id: '3-wood',
    name: '3 Wood',
    type: 'wood',
    clubSpeed: 90,
    attackAngle: -0.9,
    ballSpeed: 132,
    smash: 1.47,
    VLA: 11.2,
    spin: 2611,
    peakHeight: 23,
    descentAngle: 39,
    carry: 195,
  },
  '5-wood': {
    id: '5-wood',
    name: '5 Wood',
    type: 'wood',
    clubSpeed: 88,
    attackAngle: -1.8,
    ballSpeed: 128,
    smash: 1.47,
    VLA: 12.1,
    spin: 4501,
    peakHeight: 26,
    descentAngle: 43,
    carry: 185,
  },
  '7-wood': {
    id: '7-wood',
    name: '7 Wood',
    type: 'wood',
    clubSpeed: 85,
    attackAngle: -3.0,
    ballSpeed: 123,
    smash: 1.45,
    VLA: 12.7,
    spin: 4693,
    peakHeight: 25,
    descentAngle: 46,
    carry: 174,
  },
  '4-iron': {
    id: '4-iron',
    name: '4 Iron',
    type: 'iron',
    clubSpeed: 80,
    attackAngle: -1.7,
    ballSpeed: 116,
    smash: 1.45,
    VLA: 14.3,
    spin: 4801,
    peakHeight: 24,
    descentAngle: 43,
    carry: 169,
  },
  '5-iron': {
    id: '5-iron',
    name: '5 Iron',
    type: 'iron',
    clubSpeed: 79,
    attackAngle: -1.9,
    ballSpeed: 112,
    smash: 1.42,
    VLA: 14.8,
    spin: 5081,
    peakHeight: 23,
    descentAngle: 45,
    carry: 161,
  },
  '6-iron': {
    id: '6-iron',
    name: '6 Iron',
    type: 'iron',
    clubSpeed: 78,
    attackAngle: -2.3,
    ballSpeed: 109,
    smash: 1.39,
    VLA: 17.1,
    spin: 5943,
    peakHeight: 25,
    descentAngle: 46,
    carry: 152,
  },
  '7-iron': {
    id: '7-iron',
    name: '7 Iron',
    type: 'iron',
    clubSpeed: 76,
    attackAngle: -2.3,
    ballSpeed: 104,
    smash: 1.37,
    VLA: 19.0,
    spin: 6699,
    peakHeight: 26,
    descentAngle: 47,
    carry: 141,
  },
  '8-iron': {
    id: '8-iron',
    name: '8 Iron',
    type: 'iron',
    clubSpeed: 74,
    attackAngle: -3.1,
    ballSpeed: 100,
    smash: 1.35,
    VLA: 20.8,
    spin: 7494,
    peakHeight: 25,
    descentAngle: 47,
    carry: 130,
  },
  '9-iron': {
    id: '9-iron',
    name: '9 Iron',
    type: 'iron',
    clubSpeed: 72,
    attackAngle: -3.1,
    ballSpeed: 93,
    smash: 1.28,
    VLA: 23.9,
    spin: 7589,
    peakHeight: 26,
    descentAngle: 47,
    carry: 119,
  },
  PW: {
    id: 'PW',
    name: 'PW',
    type: 'iron',
    clubSpeed: 70,
    attackAngle: -2.8,
    ballSpeed: 86,
    smash: 1.23,
    VLA: 25.6,
    spin: 8403,
    peakHeight: 23,
    descentAngle: 48,
    carry: 107,
  },
};

export const statsForClub = (club: string, tour: string) => {
  const allStats: { [key: string]: IClub } =
    tour.toUpperCase() === 'PGA' ? pgaTourAverages : lpgaTourAverages;
  // Returns the stats for a single club
  return allStats[club];
};

export const allClubs = (tour: string) => {
  const allClubs: { [key: string]: IClub } =
    tour.toUpperCase() === 'PGA' ? pgaTourAverages : lpgaTourAverages;
  // Return all club information
  return Object.values(allClubs);
};
